name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v3
        with:
          eslint: true
          prettier: true
